namespace Mnemox.Shared.Models
{
    public enum MnemoxStatusCodes
    {
        UNAUTHORIZED = 401,
        NOT_FOUND = 404,
        INTERNAL_SERVER_ERROR = 500,
        INVALID_MODEL = 4000,
        INVALID_USERNAME_OR_PASSWORD = 4010,
        CANNOT_CONNECT_TO_THE_DATABASE = 8000,
        CANNOT_CREATE_EXTENSION = 20000,
        CANNOT_CREATE_SCHEMA = 20001,
        CANNOT_DROP_SCHEMA = 20002,
        CANNOT_RUN_QUERY = 20003,
        DATABASE_INITIALIED_ALREADY = 20004,
        CANNOT_SET_STATE_PARAMETER = 20005,
        SELECTED_SERVER_ID_ACTIVE = 30000
    }
}
